"""Memory Engine for persistent, queryable, contextual memory.

Supports 4 memory types (episodic, semantic, procedural, working)
with Qdrant vector storage (via VectorRepository) as the primary store,
falling back to in-memory dicts when Qdrant is unavailable.

Vector embeddings are generated by the configured EmbeddingClient
(OpenAI text-embedding-3-small by default, with a deterministic
fallback when no API key is configured).
"""

import logging
from typing import Any, Optional

from awren_core.embeddings import create_embedding_client
from awren_core.vector import VectorRepository, get_vector_db

logger = logging.getLogger(__name__)


class MemoryEngine:
    """Core memory engine with Qdrant-backed persistent storage and in-memory fallback.

    Stores and retrieves memories across 4 types:
    - Episodic: event-based memories of specific occurrences
    - Semantic: factual knowledge about entities and concepts
    - Procedural: knowledge of processes and workflows
    - Working: active context for current interactions

    When Qdrant is available, memories are persisted as vectors.
    Falls back gracefully to in-memory dicts when Qdrant is not reachable.
    """

    def __init__(self, vector_repo: Optional[VectorRepository] = None) -> None:
        self._vector_repo = vector_repo
        self._embedding_client = create_embedding_client()
        self._episodic: dict[str, dict[str, Any]] = {}
        self._semantic: dict[str, dict[str, Any]] = {}
        self._procedural: dict[str, dict[str, Any]] = {}
        self._working: dict[str, dict[str, Any]] = {}

    @property
    def vector_repo(self) -> Optional[VectorRepository]:
        """Lazy-initialized vector repository."""
        if self._vector_repo is None:
            try:
                get_vector_db()  # Test connection
                self._vector_repo = VectorRepository(
                    vector_size=self._embedding_client.dimensions
                )
            except Exception:
                logger.warning("Qdrant unavailable; using in-memory fallback")
        return self._vector_repo

    def _get_store(self, memory_type: str) -> dict[str, dict[str, Any]]:
        """Get the in-memory store for a given memory type."""
        mapping = {
            "episodic": self._episodic,
            "semantic": self._semantic,
            "procedural": self._procedural,
            "working": self._working,
        }
        return mapping.get(memory_type, self._semantic)

    def store(self, memory: dict[str, Any], memory_type: str = "semantic") -> str:
        """Store a memory, persisting to Qdrant if available.

        Args:
            memory: The memory dict to store. Must have a string 'id' key.
            memory_type: One of 'episodic', 'semantic', 'procedural', 'working'.

        Returns:
            The memory ID string.
        """
        mem_id = str(memory.get("id", ""))

        # Try Qdrant if available
        repo = self.vector_repo
        if repo is not None:
            try:
                vector = self._embedding_client.embed(memory.get("content", ""))
                repo.upsert(mem_id, vector, memory, memory_type=memory_type)
                return mem_id
            except Exception as e:
                logger.warning("Qdrant store failed, falling back to memory: %s", e)

        # Fallback to in-memory
        store = self._get_store(memory_type)
        store[mem_id] = memory
        return mem_id

    def retrieve(self, memory_id: str, memory_type: Optional[str] = None) -> Optional[dict[str, Any]]:
        """Retrieve a memory by ID.

        Args:
            memory_id: The unique ID of the memory.
            memory_type: Optional type filter (one of 4 types).

        Returns:
            The memory dict if found, None otherwise.
        """
        # Try Qdrant if available
        repo = self.vector_repo
        if repo is not None:
            try:
                result = repo.get(memory_id, memory_type or "semantic")
                if result is not None:
                    return result
            except Exception as e:
                logger.warning("Qdrant retrieve failed, falling back: %s", e)

        # Fallback to in-memory
        if memory_type:
            stores = [self._get_store(memory_type)]
        else:
            stores = [self._episodic, self._semantic, self._procedural, self._working]

        for store in stores:
            if memory_id in store:
                return store[memory_id]
        return None

    def query(
        self,
        query: str,
        memory_type: Optional[str] = None,
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        """Search memories by semantic similarity (Qdrant) or text match (fallback).

        Args:
            query: The search query text.
            memory_type: Optional type filter.
            limit: Maximum results to return.

        Returns:
            List of matching memory dicts.
        """
        # Try Qdrant semantic search if available
        repo = self.vector_repo
        if repo is not None:
            try:
                vector = self._embedding_client.embed(query)
                if memory_type:
                    results = repo.search(vector, memory_type=memory_type, limit=limit)
                else:
                    results = repo.search_across_types(vector, limit=limit)
                return [r.get("payload", r) for r in results]
            except Exception as e:
                logger.warning("Qdrant search failed, falling back: %s", e)

        # Fallback to in-memory text search
        if memory_type:
            stores = [self._get_store(memory_type)]
        else:
            stores = [self._episodic, self._semantic, self._procedural, self._working]

        results: list[dict[str, Any]] = []
        query_lower = query.lower()
        for store in stores:
            for mem in store.values():
                if query_lower in mem.get("content", "").lower():
                    results.append(mem)
                    if len(results) >= limit:
                        break
            if len(results) >= limit:
                break
        return results[:limit]
