"""Explainability Engine — provides structured explanations for every AI conclusion.

Every system response (chat, query, agent, reasoning result) must answer:
- WHAT: The conclusion or answer
- WHY: The reasoning that led to this conclusion
- WHICH DATA: The specific entities, relationships, and sources used
- CONFIDENCE: A score 0-1 with justification
- ASSUMPTIONS: Any assumptions made during reasoning
"""

import time
from typing import Any, Optional
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from awren_core.orm_models import EntityModel, RelationshipModel, EventModel


class Explanation:
    """Structured explanation for an AI conclusion."""

    def __init__(
        self,
        what: str,
        why: str,
        which_data: Optional[list[dict[str, Any]]] = None,
        confidence: float = 1.0,
        confidence_justification: str = "",
        assumptions: Optional[list[str]] = None,
        alternatives: Optional[list[str]] = None,
        limitations: Optional[list[str]] = None,
    ):
        self.what = what
        self.why = why
        self.which_data = which_data or []
        self.confidence = confidence
        self.confidence_justification = confidence_justification
        self.assumptions = assumptions or []
        self.alternatives = alternatives or []
        self.limitations = limitations or []

    def to_dict(self) -> dict[str, Any]:
        return {
            "what": self.what,
            "why": self.why,
            "which_data": self.which_data,
            "confidence": round(self.confidence, 2),
            "confidence_justification": self.confidence_justification,
            "assumptions": self.assumptions,
            "alternatives_considered": self.alternatives,
            "limitations": self.limitations,
        }

    def to_markdown(self) -> str:
        lines = [
            f"**Answer:** {self.what}",
            f"",
            f"**Why:** {self.why}",
            f"",
            f"**Confidence:** {self.confidence:.0%}",
        ]
        if self.confidence_justification:
            lines.append(f"  ↳ {self.confidence_justification}")
        if self.which_data:
            lines.append(f"")
            lines.append(f"**Data used:** {len(self.which_data)} sources")
            for d in self.which_data[:5]:
                lines.append(f"- {d.get('label', d.get('id', 'unknown'))} ({d.get('type', 'entity')})")
            if len(self.which_data) > 5:
                lines.append(f"- ... and {len(self.which_data) - 5} more")
        if self.assumptions:
            lines.append(f"")
            lines.append(f"**Assumptions:**")
            for a in self.assumptions:
                lines.append(f"- {a}")
        if self.limitations:
            lines.append(f"")
            lines.append(f"**Limitations:**")
            for l in self.limitations:
                lines.append(f"- {l}")
        return "\n".join(lines)


class ExplainabilityEngine:
    """Generates structured explanations for AI system outputs.

    Wraps raw responses with provenance data, confidence scoring,
    source attribution, and assumption documentation.
    """

    def __init__(self, session: Session) -> None:
        self._session = session

    # ------------------------------------------------------------------
    # Build explanations for different contexts
    # ------------------------------------------------------------------

    async def explain_chat_response(
        self,
        reply: str,
        entities_used: Optional[list[dict[str, Any]]] = None,
        actions_taken: Optional[list[dict[str, Any]]] = None,
        confidence: float = 0.85,
        model_used: str = "unknown",
        provider: str = "unknown",
    ) -> Explanation:
        """Build an explanation for a chat response."""
        which_data = []
        if entities_used:
            which_data.extend(entities_used)

        # Add action details
        if actions_taken:
            action_summary = [
                {"action": a.get("action", "unknown"), "result": a.get("message", "")}
                for a in actions_taken
            ]
            which_data.append({
                "type": "actions_executed",
                "data": action_summary,
            })

        assumptions = [
            "LLM knowledge is limited to the context provided in the system prompt",
            "Entity relationships reflect explicitly stored data only",
        ]
        if provider == "none":
            confidence = 0.0
            assumptions.append("No LLM provider is configured — response is a fallback message")

        limitations = [
            f"Response generated by {provider} model {model_used}",
            "LLM may hallucinate if insufficient context is provided",
        ]

        return Explanation(
            what=reply[:500],
            why="Response generated by LLM with knowledge graph context injected via system prompt. Actions parsed and executed in real-time.",
            which_data=which_data,
            confidence=confidence,
            confidence_justification=self._confidence_justification(confidence),
            assumptions=assumptions,
            limitations=limitations,
        )

    async def explain_search_results(
        self,
        query: str,
        results: list[dict[str, Any]],
        search_type: Optional[str] = None,
        elapsed_ms: float = 0.0,
    ) -> Explanation:
        """Build an explanation for search/query results."""
        which_data = [
            {
                "id": r.get("id"),
                "label": r.get("label", "unknown"),
                "type": r.get("type", "unknown"),
            }
            for r in results[:10]
        ]

        return Explanation(
            what=f"Found {len(results)} matching entities for query '{query}'",
            why=f"Pattern-matched entity labels and types against query '{query}' "
                f"using SQL ILIKE search{f' filtered by type: {search_type}' if search_type else ''}.",
            which_data=which_data,
            confidence=min(0.95, 0.5 + (len(results) * 0.05)),
            confidence_justification=f"Direct database query with {len(results)} results in {elapsed_ms:.0f}ms",
            assumptions=[
                "Search matches on label text only (not semantic meaning)",
                "Results ordered by creation date, not relevance",
            ],
            limitations=[
                "No semantic/vector search used — keyword matching only",
                "Does not search entity descriptions or properties",
            ],
        )

    async def explain_causal_chain(
        self,
        chains: list[dict[str, Any]],
        method: str = "graph_traversal",
    ) -> Explanation:
        """Build an explanation for causal chain analysis."""
        chain_summary = []
        for c in chains[:3]:
            chain_entities = [h.get("entity_label", h.get("entity_id", "?")) for h in (c.get("chain") or [])]
            chain_summary.append(" → ".join(chain_entities))

        which_data = [
            {"type": "causal_chains_found", "count": len(chains), "chains": chain_summary},
        ]

        if method == "llm":
            why = "LLM analyzed entity descriptions and relationships to infer causal links not explicitly stored."
            assumptions = [
                "LLM-inferred causality may not reflect actual real-world causation",
                "Confidence scores reflect linguistic patterns, not statistical correlation",
            ]
        else:
            why = "Graph traversal following 'causes', 'enables', 'triggers' relationship types."
            assumptions = [
                "Only explicit causal relationships are traversed",
                "Hidden or implicit causal links not captured",
            ]

        return Explanation(
            what=f"Discovered {len(chains)} causal chain(s) connecting entities",
            why=why,
            which_data=which_data,
            confidence=0.7 if method == "graph_traversal" else 0.5,
            confidence_justification=f"Causal chains: {len(chains)} found via {method}",
            assumptions=assumptions,
            limitations=[
                "Limited to entities in the knowledge graph",
                "Causal direction may be incorrect — correlation ≠ causation",
                f"Max {len(chains)} chains shown",
            ],
        )

    async def explain_knowledge_extraction(
        self,
        insights_created: int,
        source_text_chars: int,
    ) -> Explanation:
        """Build an explanation for knowledge extraction results."""
        return Explanation(
            what=f"Extracted {insights_created} knowledge items from {source_text_chars} characters of text",
            why="LLM analyzed text content to identify insights, rules, and patterns.",
            which_data=[{"type": "source", "size_chars": source_text_chars}],
            confidence=0.6,
            confidence_justification=f"LLM extraction — {insights_created} items created from {source_text_chars} chars",
            assumptions=[
                "LLM correctly identifies meaningful patterns vs noise",
                "Extracted knowledge may contain LLM biases",
            ],
            limitations=[
                "Extraction quality depends on LLM capabilities",
                "May miss domain-specific patterns without fine-tuning",
            ],
        )

    # ------------------------------------------------------------------
    # Wrap existing responses
    # ------------------------------------------------------------------

    def wrap_chat_response(
        self,
        reply: str,
        explanation: Explanation,
        conversation_id: str = "",
        execution_time_ms: float = 0.0,
    ) -> dict[str, Any]:
        """Wrap a chat response with explainability metadata."""
        return {
            "reply": reply,
            "conversation_id": conversation_id,
            "explanation": explanation.to_dict(),
            "execution_time_ms": round(execution_time_ms, 2),
        }

    def wrap_search_response(
        self,
        results: list[dict[str, Any]],
        explanation: Explanation,
        total: int = 0,
        elapsed_ms: float = 0.0,
    ) -> dict[str, Any]:
        """Wrap search results with explainability metadata."""
        return {
            "results": results,
            "total": total or len(results),
            "query_time_ms": round(elapsed_ms, 2),
            "explanation": explanation.to_dict(),
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _confidence_justification(self, confidence: float) -> str:
        if confidence >= 0.9:
            return "High confidence — direct data with multiple corroborating sources"
        elif confidence >= 0.7:
            return "Good confidence — supported by available data"
        elif confidence >= 0.5:
            return "Moderate confidence — partially supported, some inference involved"
        elif confidence >= 0.3:
            return "Low confidence — significant inference or limited data available"
        else:
            return "Very low confidence — mostly speculative or no data available"
